Vagrant.configure("2") do |config|
  
    config.vm.box = "ubuntu/focal64"
    config.vm.synced_folder "./..", "/vagrant"

    config.vm.provider :virtualbox do |v|
        v.customize ["modifyvm", :id, "--memory", 1048]
    end

    config.vm.provision :shell, path: "provision.sh"

    config.vm.network "forwarded_port", guest: 7010, host: 7010
end
